#-------------- User settings ------------
LIBRARIES         = argEval.3

INCLUDES          = ../../argEval.3

PROGRAM_NAMES     = example

ifndef STATICLIBNAME
STATICLIBNAME     = unknown
endif
#-----------------------------------------


include ../../Makefile.include
